''' Definitions of the shapes of the game'''
import gamecolors as colors

S_SHAPE = [['.....',
            '.....',
            '..xx.',
            '.xx..',
            '.....'],
            ['.....',
             '..x..',
             '..xx.',
             '...x.',
             '.....']]
Z_SHAPE = [['.....',
            '.....',
            '.xx..',
            '..xx.',
            '.....'],
            ['.....',
             '...x.',
             '..xx.',
             '..x..',
             '.....']]
I_SHAPE = [['..x..',
            '..x..',
            '..x..',
            '..x..',
            '.....'],
            ['.....',
             '.....',
             'xxxx.',
             '.....',
             '.....']]
O_SHAPE = [['.....',
            '.....',
            '.xx..',
            '.xx..',
            '.....']]
J_SHAPE = [['.....',
            '.x...',
            '.xxx.',
            '.....',
            '.....'],
            ['.....',
             '..x..',
             '..x..',
             '.xx..',
             '.....'],
            ['.....',
             '.....',
             '.xxx.',
             '...x.',
             '.....'],
            ['.....',
             '..xx.',
             '..x..',
             '..x..',
             '.....']]
L_SHAPE = [['.....',
            '...x.',
            '.xxx.',
            '.....',
            '.....'],
            ['.....',
             '.xx..',
             '..x..',
             '..x..',
             '.....'],
            ['.....',
             '.....',
             '.xxx.',
             '.x...',
             '.....'],
            ['.....',
             '..x..',
             '..x..',
             '..xx.',
             '.....']]
T_SHAPE = [['.....',
            '..x..',
            '.xxx.',
            '.....',
            '.....'],
            ['.....',
             '..x..',
             '.xx..',
             '..x..',
             '.....'],
            ['.....',
             '.....',
             '.xxx.',
             '..x..',
             '.....'],
            ['.....',
             '..x..',
             '..xx.',
             '..x..',
             '.....']]
SHAPES = {
    'S': 
        {"shape": S_SHAPE,
         "color": colors.GREEN},
    'I': 
        {"shape": I_SHAPE,
         "color": colors.WHITE},
    'O':
        {"shape": O_SHAPE,
         "color": colors.YELLOW},
    'Z':
        {"shape": Z_SHAPE,
         "color": colors.RED},
    'J':
        {"shape": J_SHAPE,
         "color": colors.LIGHT_BLUE},
    'L':
        {"shape":   L_SHAPE,
         "color": colors.ORANGE},
    'T':
        {"shape": T_SHAPE,
         "color": colors.PURPLE}
}
